include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: false
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    prefer_single_quotes: true
    directives_ordering: true
    unawaited_futures: true
