import 'package:flutter/material.dart';

enum JourneyToolKind {
  medicine,
  luggage,
  taskBoard,
  contacts,
  connectivity,
  dietary,
  accessibility,
  souvenirs,
  journal,
  checkpoints,
  homeReadiness,
  localKnowledge,
  visaTracker,
  travelInsurance,
  bookingConfirmations,
  flightBoarding,
  trainCoach,
  busBoarding,
  hotelStay,
  rentalInspection,
  parkingLocator,
  tollsPermits,
  fuelStops,
  restBreaks,
  meetingPoints,
  groupRoster,
  childTravel,
  seniorCare,
  petTravel,
  laundryPlan,
  waterRefills,
  deviceCharging,
  workationSetup,
  localEvents,
  weatherBackup,
  medicalFacilities,
  lostAndFound,
}

@immutable
class JourneyToolDefinition {
  const JourneyToolDefinition({
    required this.kind,
    required this.title,
    required this.description,
    required this.icon,
    required this.primaryLabel,
    required this.detailLabel,
    required this.extraLabel,
    this.canComplete = false,
    this.completionLabel = 'Done',
    this.extraIsPhone = false,
  });

  final JourneyToolKind kind;
  final String title;
  final String description;
  final IconData icon;
  final String primaryLabel;
  final String detailLabel;
  final String extraLabel;
  final bool canComplete;
  final String completionLabel;
  final bool extraIsPhone;
}

const List<JourneyToolDefinition> journeyToolDefinitions =
    <JourneyToolDefinition>[
  JourneyToolDefinition(
    kind: JourneyToolKind.medicine,
    title: 'Medicine plan',
    description: 'Keep medicine, dosage and timing together.',
    icon: Icons.medication_outlined,
    primaryLabel: 'Medicine name',
    detailLabel: 'Dosage and instructions',
    extraLabel: 'Time / schedule',
    canComplete: true,
    completionLabel: 'Taken / packed',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.luggage,
    title: 'Luggage inventory',
    description: 'Know which item is inside which bag.',
    icon: Icons.luggage_outlined,
    primaryLabel: 'Item',
    detailLabel: 'Bag or compartment',
    extraLabel: 'Quantity / identifying note',
    canComplete: true,
    completionLabel: 'Packed',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.taskBoard,
    title: 'Shared task board',
    description: 'Assign preparation work and track completion.',
    icon: Icons.group_work_outlined,
    primaryLabel: 'Task',
    detailLabel: 'Assigned to',
    extraLabel: 'Due date or note',
    canComplete: true,
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.contacts,
    title: 'Travel contacts',
    description: 'Store callable hotel, guide and local contacts.',
    icon: Icons.contact_phone_outlined,
    primaryLabel: 'Contact name',
    detailLabel: 'Role / organisation',
    extraLabel: 'Phone number',
    extraIsPhone: true,
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.connectivity,
    title: 'Connectivity plan',
    description: 'Record SIM, roaming, Wi-Fi and support details.',
    icon: Icons.sim_card_outlined,
    primaryLabel: 'Provider or plan',
    detailLabel: 'Data / roaming details',
    extraLabel: 'Support or activation note',
    canComplete: true,
    completionLabel: 'Activated',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.dietary,
    title: 'Diet and allergy card',
    description: 'Keep important food restrictions easy to show.',
    icon: Icons.restaurant_menu_outlined,
    primaryLabel: 'Restriction or allergy',
    detailLabel: 'Severity / safe alternative',
    extraLabel: 'Local-language note',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.accessibility,
    title: 'Accessibility requests',
    description: 'Track assistance requested from travel providers.',
    icon: Icons.accessible_outlined,
    primaryLabel: 'Assistance needed',
    detailLabel: 'Provider / location',
    extraLabel: 'Confirmation reference or note',
    canComplete: true,
    completionLabel: 'Confirmed',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.souvenirs,
    title: 'Gift and souvenir tracker',
    description: 'Plan recipients and budgets without duplicate buys.',
    icon: Icons.redeem_outlined,
    primaryLabel: 'Item or idea',
    detailLabel: 'For whom',
    extraLabel: 'Budget / shop note',
    canComplete: true,
    completionLabel: 'Bought',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.journal,
    title: 'Trip journal',
    description: 'Save memories, observations and useful discoveries.',
    icon: Icons.auto_stories_outlined,
    primaryLabel: 'Entry title',
    detailLabel: 'Journal entry',
    extraLabel: 'Place / date note',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.checkpoints,
    title: 'Checkpoint readiness',
    description: 'Track airport, station and border requirements.',
    icon: Icons.fact_check_outlined,
    primaryLabel: 'Checkpoint or requirement',
    detailLabel: 'Document / action needed',
    extraLabel: 'Terminal, deadline or note',
    canComplete: true,
    completionLabel: 'Ready',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.homeReadiness,
    title: 'Home departure check',
    description: 'Secure utilities, keys, pets and deliveries.',
    icon: Icons.home_work_outlined,
    primaryLabel: 'Home task',
    detailLabel: 'Responsible person',
    extraLabel: 'Deadline / instruction',
    canComplete: true,
    completionLabel: 'Secured',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.localKnowledge,
    title: 'Local knowledge notebook',
    description: 'Save verified customs, phrases and practical tips.',
    icon: Icons.psychology_alt_outlined,
    primaryLabel: 'Tip or local custom',
    detailLabel: 'Place / situation',
    extraLabel: 'Source / verification note',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.visaTracker,
    title: 'Visa requirement tracker',
    description: 'Track applications, appointments and entry conditions.',
    icon: Icons.assignment_ind_outlined,
    primaryLabel: 'Country / visa type',
    detailLabel: 'Requirement or application status',
    extraLabel: 'Deadline / reference',
    canComplete: true,
    completionLabel: 'Approved / ready',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.travelInsurance,
    title: 'Travel insurance',
    description: 'Keep policies, coverage notes and claim contacts together.',
    icon: Icons.health_and_safety_outlined,
    primaryLabel: 'Policy or provider',
    detailLabel: 'Coverage / exclusions',
    extraLabel: 'Policy number / helpline',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.bookingConfirmations,
    title: 'Booking confirmations',
    description: 'Track confirmations that still need verification.',
    icon: Icons.verified_outlined,
    primaryLabel: 'Booking',
    detailLabel: 'Provider / confirmation status',
    extraLabel: 'Reference / deadline',
    canComplete: true,
    completionLabel: 'Confirmed',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.flightBoarding,
    title: 'Flight boarding plan',
    description: 'Organise terminals, gates, seats and boarding times.',
    icon: Icons.flight_takeoff_outlined,
    primaryLabel: 'Flight / sector',
    detailLabel: 'Terminal, gate and seat',
    extraLabel: 'Boarding time / note',
    canComplete: true,
    completionLabel: 'Boarded',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.trainCoach,
    title: 'Train coach plan',
    description: 'Save platform, coach, berth and boarding details.',
    icon: Icons.train_outlined,
    primaryLabel: 'Train / journey',
    detailLabel: 'Platform, coach and berth',
    extraLabel: 'Departure / PNR note',
    canComplete: true,
    completionLabel: 'Boarded',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.busBoarding,
    title: 'Bus boarding plan',
    description: 'Keep pickup points, bus details and operator contacts.',
    icon: Icons.directions_bus_outlined,
    primaryLabel: 'Bus / route',
    detailLabel: 'Pickup point and vehicle details',
    extraLabel: 'Time / operator contact',
    canComplete: true,
    completionLabel: 'Boarded',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.hotelStay,
    title: 'Hotel stay organiser',
    description: 'Track check-in, room requests and checkout tasks.',
    icon: Icons.hotel_outlined,
    primaryLabel: 'Hotel / stay',
    detailLabel: 'Check-in and room requirement',
    extraLabel: 'Confirmation / checkout note',
    canComplete: true,
    completionLabel: 'Handled',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.rentalInspection,
    title: 'Rental inspection',
    description: 'Record vehicle condition, fuel level and return obligations.',
    icon: Icons.car_rental_outlined,
    primaryLabel: 'Rental vehicle',
    detailLabel: 'Existing damage / inspection note',
    extraLabel: 'Fuel / return deadline',
    canComplete: true,
    completionLabel: 'Returned',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.parkingLocator,
    title: 'Parking locator',
    description: 'Remember parking level, bay, landmark and expiry.',
    icon: Icons.local_parking_outlined,
    primaryLabel: 'Parking place',
    detailLabel: 'Level, bay or nearby landmark',
    extraLabel: 'Expiry / fee note',
    canComplete: true,
    completionLabel: 'Vehicle collected',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.tollsPermits,
    title: 'Tolls and permits',
    description: 'Track road permits, toll passes and payment status.',
    icon: Icons.toll_outlined,
    primaryLabel: 'Toll / permit',
    detailLabel: 'Route and requirement',
    extraLabel: 'Cost / validity',
    canComplete: true,
    completionLabel: 'Paid / obtained',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.fuelStops,
    title: 'Fuel stop planner',
    description: 'Plan reliable fuel or charging stops along the route.',
    icon: Icons.local_gas_station_outlined,
    primaryLabel: 'Stop name',
    detailLabel: 'Location / fuel or charger type',
    extraLabel: 'Distance / operating note',
    canComplete: true,
    completionLabel: 'Completed',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.restBreaks,
    title: 'Rest break planner',
    description: 'Schedule safer breaks for long road journeys.',
    icon: Icons.airline_seat_recline_normal_outlined,
    primaryLabel: 'Break location',
    detailLabel: 'Facilities / driver change',
    extraLabel: 'Target time / distance',
    canComplete: true,
    completionLabel: 'Break taken',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.meetingPoints,
    title: 'Group meeting points',
    description: 'Save precise regroup locations and fallback instructions.',
    icon: Icons.location_on_outlined,
    primaryLabel: 'Meeting point',
    detailLabel: 'Exact landmark / directions',
    extraLabel: 'Time / fallback point',
    canComplete: true,
    completionLabel: 'Group reunited',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.groupRoster,
    title: 'Traveller roster',
    description: 'Track who is joining each leg without exposing it publicly.',
    icon: Icons.groups_outlined,
    primaryLabel: 'Traveller name',
    detailLabel: 'Journey leg / responsibility',
    extraLabel: 'Contact or note',
    canComplete: true,
    completionLabel: 'Checked in',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.childTravel,
    title: 'Child travel care',
    description: 'Organise child documents, meals, comfort and supervision.',
    icon: Icons.child_care_outlined,
    primaryLabel: 'Child / requirement',
    detailLabel: 'Care instruction or item',
    extraLabel: 'Timing / responsible adult',
    canComplete: true,
    completionLabel: 'Ready',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.seniorCare,
    title: 'Senior travel care',
    description: 'Plan mobility, medicine, rest and assistance needs.',
    icon: Icons.elderly_outlined,
    primaryLabel: 'Traveller / requirement',
    detailLabel: 'Assistance or health note',
    extraLabel: 'Timing / responsible person',
    canComplete: true,
    completionLabel: 'Arranged',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.petTravel,
    title: 'Pet travel organiser',
    description: 'Track pet documents, carrier, food and provider rules.',
    icon: Icons.pets_outlined,
    primaryLabel: 'Pet / requirement',
    detailLabel: 'Document, carrier or care note',
    extraLabel: 'Deadline / provider rule',
    canComplete: true,
    completionLabel: 'Ready',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.laundryPlan,
    title: 'Laundry planner',
    description: 'Plan laundry stops and avoid unnecessary over-packing.',
    icon: Icons.local_laundry_service_outlined,
    primaryLabel: 'Laundry task / location',
    detailLabel: 'Clothes, service or instructions',
    extraLabel: 'Date / price note',
    canComplete: true,
    completionLabel: 'Cleaned',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.waterRefills,
    title: 'Water refill plan',
    description: 'Record trusted refill points and hydration stops.',
    icon: Icons.water_drop_outlined,
    primaryLabel: 'Refill point',
    detailLabel: 'Location / water availability',
    extraLabel: 'Opening time / quantity',
    canComplete: true,
    completionLabel: 'Refilled',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.deviceCharging,
    title: 'Device charging plan',
    description: 'Track sockets, adapters, power banks and charging stops.',
    icon: Icons.battery_charging_full_outlined,
    primaryLabel: 'Device / charging point',
    detailLabel: 'Adapter, cable or location',
    extraLabel: 'Target charge / time',
    canComplete: true,
    completionLabel: 'Charged',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.workationSetup,
    title: 'Workation setup',
    description: 'Organise workspace, connectivity and meeting commitments.',
    icon: Icons.laptop_mac_outlined,
    primaryLabel: 'Work requirement',
    detailLabel: 'Workspace / connection details',
    extraLabel: 'Time zone / deadline',
    canComplete: true,
    completionLabel: 'Ready',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.localEvents,
    title: 'Local event planner',
    description: 'Save verified events, timings, tickets and venue notes.',
    icon: Icons.event_available_outlined,
    primaryLabel: 'Event',
    detailLabel: 'Venue / ticket details',
    extraLabel: 'Date / source',
    canComplete: true,
    completionLabel: 'Attended',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.weatherBackup,
    title: 'Bad-weather backup',
    description: 'Keep an indoor alternative for weather-sensitive plans.',
    icon: Icons.umbrella_outlined,
    primaryLabel: 'Original plan',
    detailLabel: 'Indoor or safer alternative',
    extraLabel: 'Trigger / booking note',
    canComplete: true,
    completionLabel: 'Backup ready',
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.medicalFacilities,
    title: 'Medical facility list',
    description: 'Keep nearby clinics, hospitals and pharmacy details.',
    icon: Icons.local_hospital_outlined,
    primaryLabel: 'Facility name',
    detailLabel: 'Speciality, address and opening note',
    extraLabel: 'Phone number',
    extraIsPhone: true,
  ),
  JourneyToolDefinition(
    kind: JourneyToolKind.lostAndFound,
    title: 'Lost and found tracker',
    description: 'Record missing items, reports and recovery follow-ups.',
    icon: Icons.find_in_page_outlined,
    primaryLabel: 'Missing item',
    detailLabel: 'Last seen / identifying details',
    extraLabel: 'Report number / contact',
    canComplete: true,
    completionLabel: 'Recovered / closed',
  ),
];

JourneyToolDefinition definitionFor(JourneyToolKind kind) =>
    journeyToolDefinitions.firstWhere(
      (JourneyToolDefinition item) => item.kind == kind,
    );

@immutable
class JourneyOperation {
  const JourneyOperation({
    required this.id,
    required this.userId,
    required this.kind,
    required this.title,
    required this.detail,
    required this.extra,
    required this.completed,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String userId;
  final JourneyToolKind kind;
  final String title;
  final String detail;
  final String extra;
  final bool completed;
  final DateTime createdAt;
  final DateTime updatedAt;

  JourneyOperation copyWith({bool? completed}) => JourneyOperation(
        id: id,
        userId: userId,
        kind: kind,
        title: title,
        detail: detail,
        extra: extra,
        completed: completed ?? this.completed,
        createdAt: createdAt,
        updatedAt: DateTime.now(),
      );

  Map<String, dynamic> toFirestore() => <String, dynamic>{
        'id': id,
        'userId': userId,
        'kind': kind.name,
        'title': title,
        'detail': detail,
        'extra': extra,
        'completed': completed,
        'createdAt': createdAt.millisecondsSinceEpoch,
        'updatedAt': updatedAt.millisecondsSinceEpoch,
      };

  static JourneyOperation fromFirestore(Map<String, dynamic> data) {
    final String kindName = (data['kind'] as String?) ?? '';
    return JourneyOperation(
      id: (data['id'] as String?) ?? '',
      userId: (data['userId'] as String?) ?? '',
      kind: JourneyToolKind.values.firstWhere(
        (JourneyToolKind kind) => kind.name == kindName,
        orElse: () => JourneyToolKind.taskBoard,
      ),
      title: (data['title'] as String?) ?? '',
      detail: (data['detail'] as String?) ?? '',
      extra: (data['extra'] as String?) ?? '',
      completed: (data['completed'] as bool?) ?? false,
      createdAt: DateTime.fromMillisecondsSinceEpoch(
        ((data['createdAt'] as num?) ?? 0).toInt(),
      ),
      updatedAt: DateTime.fromMillisecondsSinceEpoch(
        ((data['updatedAt'] as num?) ?? 0).toInt(),
      ),
    );
  }
}
