import 'itinerary.dart';

/// A saved, editable trip plan generated by the AI planner and stored
/// on-device (offline-first). Contains the destination coordinates so the
/// Home screen and Live Trip mode can route to it without a backend.
class TripPlan {
  TripPlan({
    required this.id,
    required this.destination,
    required this.lat,
    required this.lng,
    required this.startDate,
    required this.days,
    required this.budget,
    required this.travelStyle,
    required this.transport,
    required this.partySize,
    required this.interests,
    required this.plan,
    required this.createdAt,
  });

  final String id;
  final String destination;

  /// Destination coordinates (resolved from a real place search when the
  /// plan is saved; 0/0 when the user typed a destination without picking a
  /// search result).
  final double lat;
  final double lng;
  final DateTime startDate;
  final int days;
  final String budget;
  final String travelStyle;
  final String transport;
  final int partySize;
  final List<String> interests;
  final List<ItineraryDay> plan;
  final DateTime createdAt;

  bool get hasCoordinates => lat != 0 || lng != 0;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'id': id,
        'destination': destination,
        'lat': lat,
        'lng': lng,
        'startDate': startDate.toIso8601String(),
        'days': days,
        'budget': budget,
        'travelStyle': travelStyle,
        'transport': transport,
        'partySize': partySize,
        'interests': interests,
        'plan': plan.map((ItineraryDay d) => d.toMap()).toList(),
        'createdAt': createdAt.toIso8601String(),
      };

  factory TripPlan.fromJson(Map<String, dynamic> m) {
    final List<dynamic> rawPlan =
        (m['plan'] is List) ? m['plan'] as List : <dynamic>[];
    return TripPlan(
      id: m['id'] as String? ?? '',
      destination: (m['destination'] as String?) ?? 'Trip',
      lat: (m['lat'] as num?)?.toDouble() ?? 0,
      lng: (m['lng'] as num?)?.toDouble() ?? 0,
      startDate:
          DateTime.tryParse(m['startDate'] as String? ?? '') ?? DateTime.now(),
      days: (m['days'] as num?)?.toInt() ?? 1,
      budget: (m['budget'] as String?) ?? 'mid',
      travelStyle: (m['travelStyle'] as String?) ?? 'balanced',
      transport: (m['transport'] as String?) ?? 'car',
      partySize: (m['partySize'] as num?)?.toInt() ?? 1,
      interests: (m['interests'] is List)
          ? (m['interests'] as List).whereType<String>().toList()
          : <String>[],
      plan: rawPlan
          .whereType<Map<String, dynamic>>()
          .map(ItineraryDay.fromMap)
          .toList(),
      createdAt:
          DateTime.tryParse(m['createdAt'] as String? ?? '') ?? DateTime.now(),
    );
  }
}
